# Generated by Django 4.2.11 on 2024-04-21 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_alter_artist_nickname_alter_artwork_image_url_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artwork',
            name='image_url',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='avatar',
            field=models.TextField(blank=True),
        ),
    ]
