name: Run Django Tests

on: [push, pull_request]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.10"]
      
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Print current directory
        run: pwd
      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install Dependencies
        run: |
          cd backend
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Run Tests
        run: |
          cd backend
          python manage.py test --noinput api.test-api.test-api
